# This file is generated by packaging/homebrew/generate_formula.py.
# Do not edit by hand; regenerate it after each bunkerie release.
class Bunkerie < Formula
  desc "Encrypted off-device backup for AI agent context files"
  homepage "https://bunkerie.com"
  version "0.0.7"
  license "MIT"

  on_macos do
    on_arm do
      url "https://dl.bunkerie.com/releases/v0.0.7/bunkerie_v0.0.7_darwin_arm64.tar.gz"
      sha256 "229094ba9435ba8da81a091e429a5bc76a775d3c5b50e3ab78388c68d8a29b74"
    end

    on_intel do
      url "https://dl.bunkerie.com/releases/v0.0.7/bunkerie_v0.0.7_darwin_amd64.tar.gz"
      sha256 "0ba8f5bacd4d8f038603ea43d8d824d3f67d4597f95c5b71a315d86e12319d8c"
    end
  end

  on_linux do
    on_arm do
      url "https://dl.bunkerie.com/releases/v0.0.7/bunkerie_v0.0.7_linux_arm64.tar.gz"
      sha256 "09d119bb5c8d8011c1a40480fdf4c2caaa90c8274da33657f99b07d0549279a7"
    end

    on_intel do
      url "https://dl.bunkerie.com/releases/v0.0.7/bunkerie_v0.0.7_linux_amd64.tar.gz"
      sha256 "038bbeb36cdf447f31b86ad4c3a9194af8dde0d096484e728e8ef944699ae87d"
    end
  end

  def install
    bin.install "bunkerie"
  end

  def caveats
    <<~EOS
      Update Homebrew installations with:
        brew upgrade seetie-ai/bunkerie/bunkerie
    EOS
  end

  test do
    assert_match "bunkerie", shell_output("#{bin}/bunkerie help")
  end
end
