# This file is generated by packaging/homebrew/generate_formula.py.
# Do not edit by hand; regenerate it after each bunkerie release.
class Bunkerie < Formula
  desc "Encrypted off-device backup for AI agent context files"
  homepage "https://bunkerie.com"
  version "0.0.10"
  license "MIT"

  on_macos do
    on_arm do
      url "https://dl.bunkerie.com/releases/v0.0.10/bunkerie_v0.0.10_darwin_arm64.tar.gz"
      sha256 "884555752f3dd1d6ee932ca035e46bf5c0b976af4f53a3eaaeb7652859aa39e1"
    end

    on_intel do
      url "https://dl.bunkerie.com/releases/v0.0.10/bunkerie_v0.0.10_darwin_amd64.tar.gz"
      sha256 "db0d580ed5ac2281419b01fe3a1105fc5b0a379b966308cd7bfd167a06bdc83f"
    end
  end

  on_linux do
    on_arm do
      url "https://dl.bunkerie.com/releases/v0.0.10/bunkerie_v0.0.10_linux_arm64.tar.gz"
      sha256 "4dde4b64f9688bc3544a3129e8776c7c9a2867a6e73bc2768c62734de3792b30"
    end

    on_intel do
      url "https://dl.bunkerie.com/releases/v0.0.10/bunkerie_v0.0.10_linux_amd64.tar.gz"
      sha256 "6546fc192b34b3e4daae945dda49a459f58bc45a3d6f23995196c974740e210b"
    end
  end

  def install
    bin.install "bunkerie"
  end

  def caveats
    <<~EOS
      Update Homebrew installations with:
        brew upgrade seetie-ai/bunkerie/bunkerie
    EOS
  end

  test do
    assert_match "bunkerie", shell_output("#{bin}/bunkerie help")
  end
end
